site_name: SportLudique Bourges
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
